<?php
/**
 * Created by PhpStorm.
 * User: Max
 * Date: 11.08.2017
 * Time: 19:17
 */

namespace Corp\Repositories;

use Corp\Portfolio;

class PortfoliosRepository extends Repository
{
    /**
     * PortfoliosRepository constructor.
     */
    public function __construct(Portfolio $portfolio)
    {
        $this->model = $portfolio;
    }

    public function one($alias, $attr = [])
    {
        $portfolio = parent::one($alias, $attr); // TODO: Change the autogenerated stub

        if ($portfolio && $portfolio->img) {
            $portfolio->img = json_decode($portfolio->img);
        }

        return $portfolio;
    }


}